-- Script generated by GameGuardian 76.1 (14712) at 2019-05-06 23:16:16 for 明日方舟 [com.hypergryph.arknights.bilibili 0.7.27 (3)]
-- Lua help: http://gameguardian.net/help/

-- options
local scriptName = [=====[Script for 明日方舟 0.7.27]=====]
local scriptVersion = '1.0.0'
local scriptAuthor = 'User'
local startToast = ''
-- 0 - no check; 1 - check package only, 2 - check package and build
local checkTarget = 0

local targetName = [=====[明日方舟]=====]
local targetPkg = 'com.hypergryph.arknights.bilibili'
local targetVersion = [=====[0.7.27]=====]
local targetBuild = 3

-- functions

-- init
gg.require('76.1', 14712)

if startToast ~= '' then startToast = '\n'..startToast end
gg.toast(scriptName..' v'..scriptVersion..' by '..scriptAuthor..startToast)

if checkTarget ~= 0 then
	local info = gg.getTargetInfo()
	local check = false
	local current = false
	if checkTarget >= 1 then
		check = targetPkg
		current = info.packageName
	end
	if checkTarget >= 2 then
		check = check..' '..targetVersion..' ('..targetBuild..')'
		current = current..' '..info.versionName..' ('..info.versionCode..')'
	end
	if check ~= current then
		gg.alert('This script for "'..targetName..'" ['..check..'].\nYou select "'..info.label..'" ['..current..'].\nNow script exit.')
		os.exit()
	end
end
local revert = nil

-- main code
gg.searchNumber('"-1.5;-0.5;1;2;2.5;3:512"', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber('"1;2;2.5;3:512"', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(9999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"50"', gg.TYPE_FLOAT)
gg.processResume()

gg.clearResults()
gg.searchNumber('"-1.5;-0.5;4:512"', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber('"4"', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(9999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"50"', gg.TYPE_FLOAT)

gg.clearResults()
gg.searchNumber('"-1.5;-0.5;50:512"', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.refineNumber('"-1.5;-0.5:512"', gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
revert = gg.getResults(9999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"-5"', gg.TYPE_FLOAT)
gg.processResume()
revert = gg.getResults(9999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll('"-10"', gg.TYPE_FLOAT)
gg.processResume()
