gg.setVisible(false)
gg.clearResults()
gg.setRanges(32)
gg.searchNumber("16;59;230", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber("16", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100)
gg.editAll("10000", gg.TYPE_FLOAT)
gg.toast("开锁完美开启成功")
gg.clearResults()
gg.setRanges(32)
gg.searchNumber("-280;-160;230;2;0.2::17", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100)
gg.editAll("0", gg.TYPE_FLOAT)
gg.toast("光速开锁开启成功")
gg.clearResults()
gg.searchNumber("0.3;10", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.searchNumber("0.3", gg.TYPE_FLOAT, false, gg.SIGN_EQUAL, 0, -1)
gg.getResults(100)
gg.editAll("10000", gg.TYPE_FLOAT)
gg.toast("100开机概率开启成功")
gg.clearResults()