-- Script generated by GameGuardian 83.0 (15206) at 2021-04-11 16:08:22 for 王者荣耀 [com.tencent.tmgp.sgame 3.63.1.5 (363010502)]
-- Lua help: http://gameguardian.net/help/

-- options
local scriptName = [=====[Script for 王者荣耀 3.63.1.5]=====]
local scriptVersion = '1.0.0'
local scriptAuthor = 'User'
local startToast = ''
-- 0 - no check; 1 - check package only, 2 - check package and build
local checkTarget = 0

local targetName = [=====[王者荣耀]=====]
local targetPkg = 'com.tencent.tmgp.sgame'
local targetVersion = [=====[3.63.1.5]=====]
local targetBuild = 363010502

-- functions

-- init
gg.require('83.0', 15206)

if startToast ~= '' then startToast = '\n'..startToast end
gg.toast(scriptName..' v'..scriptVersion..' by '..scriptAuthor..startToast)

if checkTarget ~= 0 then
	local info = gg.getTargetInfo()
	local check = false
	local current = false
	if checkTarget >= 1 then
		check = targetPkg
		current = info.packageName
	end
	if checkTarget >= 2 then
		check = check..' '..targetVersion..' ('..targetBuild..')'
		current = current..' '..info.versionName..' ('..info.versionCode..')'
	end
	if check ~= current then
		gg.alert('This script for "'..targetName..'" ['..check..'].\nYou select "'..info.label..'" ['..current..'].\nNow script exit.')
		os.exit()
	end
end
local revert = nil

-- main code

gg.clearResults()
gg.searchNumber("-1736865558;-109308169", gg.TYPE_DWORD, false, gg.SIGN_EQUAL, 0, -1)
gg.processResume()
revert = gg.getResults(99999, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll("-2051403109;1243391857", gg.TYPE_DWORD)
