-- Script generated by GameGuardian 76.1 (14712) at 2020-09-30 22:05:53 for 王牌战争 [com.yingxiong.gw.Android.hero 5.4 (54)]
-- Lua help: http://gameguardian.net/help/

-- options
local scriptName = [=====[Script for 王牌战争 5.4]=====]
local scriptVersion = '1.0.0'
local scriptAuthor = 'User'
local startToast = ''
-- 0 - no check; 1 - check package only, 2 - check package and build
local checkTarget = 0

local targetName = [=====[王牌战争]=====]
local targetPkg = 'com.yingxiong.gw.Android.hero'
local targetVersion = [=====[5.4]=====]
local targetBuild = 54

-- functions

-- init
gg.require('76.1', 14712)

if startToast ~= '' then startToast = '\n'..startToast end
gg.toast(scriptName..' v'..scriptVersion..' by '..scriptAuthor..startToast)

if checkTarget ~= 0 then
	local info = gg.getTargetInfo()
	local check = false
	local current = false
	if checkTarget >= 1 then
		check = targetPkg
		current = info.packageName
	end
	if checkTarget >= 2 then
		check = check..' '..targetVersion..' ('..targetBuild..')'
		current = current..' '..info.versionName..' ('..info.versionCode..')'
	end
	if check ~= current then
		gg.alert('This script for "'..targetName..'" ['..check..'].\nYou select "'..info.label..'" ['..current..'].\nNow script exit.')
		os.exit()
	end
end
local revert = nil

-- main code
gg.processResume()
